### ISSUE TITLE
Millilitre won't work with SimpleUnitFormat

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/uom-se#114]
While SimpleUnitFormat

**Comment by lfoppiano** [comment]
I write some comments here, because I think is worth it to discuss a little before. 
I did not have the problem with the SimpleUnitFormat. The unit tests that are failing because when the liter is created in the following way: 
```
    public static final Unit<Volume> LITRE = addUnit(new TransformedUnit<>(
            CUBIC_METRE, new RationalConverter(1, 1000)));
```
therefore liter are created as TransformedUnit, but with the Parent of a different nature. Is is created as as CUBIC_METERS. Liters are liters, but could also be translated in cubic meters as a specific operation, for example when normalized. 

Said that, maybe it should considered as an AlternateUnit? The problem is that the transformation rate is not 1:1 but is 0.001. So perhaps having AlternateUnit with a ConvertionRate as well that is applied when passing from one to the other?
@keilw, what do you think?

**Comment by keilw** [comment]
Sorry, AlternateUnit won't work at all. If you look at its implementation, trying to apply it to a derived unit like Volume it fails with "the parent unit is not an unscaled SI unit". The way it's added is exactly identical in RI and uom-se now, won't make a difference, but in the RI this works, so it's now how the unit is declared in the unit system.

**Comment by lfoppiano** [comment]
Indeed. I was just speculating. In fact there are slights differences in the two libraries. I'm still working on it. ;-)

**Comment by keilw** [comment]
Ok, I also noticed the class is slightly different, to some extent because one needs to be Java ME compatible, but if you find a piece in the RI that makes the SE port work, happy to see a PR.

**Comment by lfoppiano** [comment]
Just to update you (it's a hell of a bug :)), and have feedback (if you have it). :) 
I've narrow the problem until here: 
```
    Map<Unit<?>, String > map = new HashMap<>();

    final Unit<Volume> milli = MILLI(LITRE);
    map.put(milli, "ml");
    System.out.println(map.get(milli));   // return the correct value
    System.out.println(map.get(MILLI(LITRE)));   // returns null

    final Unit<Volume> litre = LITRE;
    map.put(litre, "l");
    System.out.println(map.get(litre));    //return the correct value
    System.out.println(map.get(LITRE));    //return the correct value
```
I believe is an issue with the hashCode... in particular with the hashCode of the parentUnit.

**Comment by keilw** [comment]
At least these are different. @otaviojava tried to leverage Java 8 for uom-se so hashcode() uses an `Objects.hashcode() ` helper method. That is not available in Java SE 7 or ME 8, so you'll often find the available criteria like "symbol", "name" or both are used instead. We probably have to harmonize that by porting the exact code in the RI instead of such "Voodoo", since it does make us dependent on changes to the `Objects `class while otherwise we have full control in our own classes. Thanks for analyzing that so far.

**Comment by lfoppiano** [comment]
I think that using `Objects.hashcode()` is not a bad approach. Here the problem is happearing by every variation of LITRE. I don't think the `Object` class has changed behaviour, if I replace it with 
`parentUnit.hashCode()` it doesn't solve the problem. 

I still cannot understand why METRE and LITRE don't behave the same way... Seems that something happens when MILLI is created and the transform() method is called.

**Comment by keilw** [comment]
The probblem is `Objects.hashcode()` is not portable, so unless you pull all of its code into the RI somewhere it's not an option there. MILLI must behave the same for both, there is just one method. However LITRE is not a `BaseUnit` for sure, so that might explain a different behavior. Maybe one has to try other variants like MILLI(GRAM) (I recall it works) or different quantities to be on the safe side.

Both uom-se and the RI can use a whole lot of test coverage, so far meager ~35-37% ;-|

**Comment by lfoppiano** [comment]
Ah, I see your point. uom-se should 'incubating' code that will be ported to unit-ri. 
So the problem is that `LITRE` is a TransformedUnit with a parent which is a `ProductUnit`. For `ProductUnit` the hashCode is calculated by calculating the hashCode of the elements (of type `ProductUnit.Element`). 

I've generated hashCode() method for this class and seems to work properly. PR to come.
