### ISSUE TITLE
Parsing of BaseUnits (e.g. 'm')

### ISSUE THREAD

**Issue by lfoppiano** [unitsofmeasurement/uom-se#118]
Hi, 
   I have a simple question, I've noticed that basic unit are not parsed from the SimpleUnitFormat. For example "m" it is not recognized. 

Here a sample, of my current code: 

```
UnitFormatService formatService = Bootstrap.getService(UnitFormatService.class);
UnitFormat defaultFormatService = formatService.getUnitFormat();
Unit parsedUnit = defaultFormatService.parse("m");
```
It works with composed unit, like `km` but not with `m` or `s`. 
What would be the best practice? Is there a way to achieve this parsing? 

Thanks
Luca

**Comment by lfoppiano** [comment]
I've compared the uom-se with the unit-ri implementation and I've noticed that the `_nameToUnit` Map of the two libraries contains different elements (seems that uom-se doesn't cover as much as unit-ri). 

Is this normal? In the meantime I'm going to investigate further...

**Comment by keilw** [comment]
it is normal and possible. Especially since the RI is a mandatory JSR artifact while  uom-se is a collaborative effort to use the API with additional features of Java SE and Java 8 like Lambdas, BigDecimal or java.time. You'll see code in uom-se that makes no sense in the RI (won't run on Java ME) and in some cases the RI will have different or other code possibly even in the same class. Except for a known problem with "ml" (see JUnit tests or https://github.com/unitsofmeasurement/uom-se/issues/114) all other tests pass here and they completely pass for the RI. If you think one could be missing, please suggest something here. PRs are fine here, also for non EG-members.

**Comment by lfoppiano** [comment]
OK, just to be sure before starting modifying code :)
I'll send you a PR on both issues.

**Comment by keilw** [comment]
Sure, if you solve the unit test failures or other issues please do.

**Comment by lfoppiano** [comment]
Sure. 
For the other units above, what did you mean? Is it normal that they are not parsed, or if is normal that they are missing (and should be added)?

**Comment by keilw** [comment]
It schould work for base units like m or s, too.
