### ISSUE TITLE
protected EBNFUnitFormat getInstance

### ISSUE THREAD

**Issue by johannnnnnnn** [unitsofmeasurement/uom-se#144]
I tested and compared all unit formatting an parsing possibilities offered by UoM and the outcome is: EBNFUnitFormat is by far the best - we want to use it.

There is just one wish or question:
Why is `getInstance(SymbolMap symbols, Locale locale)` protected ?

I want to use my own SymbolMap.

Is there a reason why this cannot be public ?

**Comment by keilw** [comment]
Hi, yes, `EBNFUnitFormat` is a bit more powerful than SimpleUnitFormat, the latter helps to keep this implementation compatible with the RI and Java ME Embedded. Depending on the future or Java ME we may have to reconsider that in the future. 
Right now `SymbolMap` is a `final` class, so it would not be possible to have your own even if we made such method public. It is a bit of a legacy from JSR 275, see https://github.com/unitsofmeasurement/jsr-275/tree/master/src/main/java/javax/measure/unit where `SymbolMap` was an interface in the API. Many of these elements were either moved into implementations (like in this case) or simplified, e.g. `label()` and other methods that are now directly on `UnitFormat` instead of elemements within such as `SymbolMap` implementations. If there is a case for making SymbolMap at least a non-final class or more, please add a similar ticket for that describing the requirement.

Thanks,
Werner

**Comment by johannnnnnnn** [comment]
Yes, you are right.

I meant, we want to use our own messages.properties and instantiate a SymbolMap of it - and then call the getInstance(SymbolMap).

**Comment by keilw** [comment]
Yo may have noticed, there is a public method like that in `LocalUnitformat`. Which is very similar to `EBNFUnitFormat` except it is locale-sensitive. That is a main reason why the method taking a locale is protected in `EBNFUnitFormat`. We have to take a closer look at it, some overlap between `LocalUnitFormat` and `EBNFUnitFormat` could be reduced and improved. They meet similar goals, the only difference is, that one is not meant to behave different for different locales and languages, while the other can. Is a single locale currently enough for you?

**Comment by keilw** [comment]
Actually I think you only need one argument. The Locale is redundant or even ignored. Since `EBNFUnitFormat` is not meant to support more than one locale or language, is that fine for you? I'm inclined to try simplify them by making `LocalUnitFormat` ultimately extend `EBNFUnitFormat` but any locale switching or arguments would be mostly hidden from `EBNFUnitFormat` because it is not locale-sensitive.

**Comment by johannnnnnnn** [comment]
Yes, I saw this.

But I have problems with LocalUnitFormat when parsing Units like '10E3/ml' (we have lots of very funny Units coming from devices). EBNFUnitFormat can parse them all. And we just have one language.

**Comment by keilw** [comment]
It is not so common I agree. And to fully tap into large scale i18n we'd have to use e.g. Unicode CLDR (which has its own module: https://github.com/unitsofmeasurement/uom-systems/tree/master/unicode-java8) I am not fully deciced on that one, maybe we have to ask a question ticket, one possible scenario could be pruning/removing the LocalUnitFormat here and offering a more flexible one in the systems-unicode extension module (including a custom `UnitFormat`)
