### ISSUE TITLE
Temperature units inconsistencies

### ISSUE THREAD

**Issue by jillesvangurp** [unitsofmeasurement/uom-se#163]
I noticed a few inconsistencies with the temperature units:

```
Units.CELSIUS.toString();
=> C
Units.KELVIN.toString();
=> K
USCustomary.FAHRENHEIT.toString()
=> °F, expected would be F

Units.CELSIUS.getSymbol();
=> K, expected would be °C
```
This is with v1.0.2

**Comment by keilw** [comment]
Can you check 1.0.7, please? 
As defined by the `Unit` interface,` getSymbol()` does not represent the unit itself in many cases of derived units. So `CELSIUS` referring to `KELVIN` here is perfectly fine, but as `TransformedUnit` has undergone some changes you may see null returned instead.

The default format for `CELSIUS` should be "°C" for some time now.

**Comment by keilw** [comment]
At least since uom-se 1.0.6 it works perfectly fine. See https://github.com/unitsofmeasurement/uom-demos/blob/master/console/systems/common-java8/src/main/java/tec/uom/demo/se/systems/common/TemperatureDemo.java

```
Temperature Demo
℃
null
K
K
°F
null
```

`getSymbol()` is `null` except for `KELVIN` (a base unit)
Closing this ticket as it works, please use a recent version, at least 1.0.6 if you can.

**Comment by jillesvangurp** [comment]
Thanks; I found some unrelated issues with 1.0.7. I'll file a separate ticket for that.

**Comment by keilw** [comment]
Thanks, please do, we'll take them into consideration for further releases.

**Comment by jillesvangurp** [comment]
Nevermind, turns out I had a dependency issues. Thanks again for your fixes.
