### ISSUE TITLE
getSymbol does not return proper string for divide

### ISSUE THREAD

**Issue by marois** [unitsofmeasurement/uom-se#184]
I'm trying to create a new derived unit, molar, but the symbol return "mol" instead of "mol/m3". `toString()` does work returning "mol/m³"

`assertEquals("mol/m3", Units.MOLE.divide(Units.CUBIC_METRE));`

**Comment by keilw** [comment]
Hi, the subject mentions `getSymbol()`, the body `toString()`. Which method are you trying to use?

**Comment by marois** [comment]
Sorry didn't proofread before submitting. The failing assert should have been `assertEquals("mol/m3", Units.MOLE.divide(Units.CUBIC_METRE).getSymbol());` 
The getSymbol() function returns "mol" but should return something like "mol/m3". The toString() method does return a properly constructed unit.

**Comment by keilw** [comment]
Hi, This is addressed by not putting any symbol in case of a `ProductUnit`. Note, that `assertNull(Units.MOLE.divide(Units.CUBIC_METRE).getSymbol());` is correct in this case. Some possible left-over used the first element only. Which worked again only because `MOLE` is a `BaseUnit`. The spec/JavaDoc http://unitsofmeasurement.github.io/unit-api/site/apidocs/javax/measure/Unit.html#getSymbol() is clear as it says, this could and usually should be null for a product of units. Please use `toString()` only in this case unless dealing with a particular type of unit like a `BaseUnit` that has a distinct symbol.

**Comment by marois** [comment]
I understand the explanation. Just not sure I understand the rationale for
the requirement not to return the symbol for a ProductUnit, since it
clearly can be derived based on the implementation of toString.

How would you suggest adding MolarConcentration, aka "substance
concentration" (https://www.bipm.org/en/publications/si-brochure/mole.html)?
I'm currently adding it as a ProductionUnit to our `LifeScienceUnits extend
Units` and setting it's label in a static code block.

Jean

**Comment by keilw** [comment]
Jean, That is the right approach for extended or custom unit system. Where applicable we do this just the same way for SI or other systems. 

The definition of `symbol` vs. `label` (and in some cases `alias`, though it is not part of the API) existed for some time. `getSymbol()` was not even there in the very first approach JSR 108: http://jsr-108.sourceforge.net/javadoc/javax/units/Unit.html. Therefore `toString()` has always been the preferred way of visual representation for a unit.

**Comment by marois** [comment]
Ok thanks for the clarification. I was confused.
