### ISSUE TITLE
How stable is this project ATM? 

### ISSUE THREAD

**Issue by feliksik** [unitsofmeasurement/uom-se#187]
This seems like a mighty good project; but how stable is it at the moment? I see that the JSR 385 has just recently been finished. 

For non-experimental stuff, do you recommend working with the 'old' 1.0 API (I believe JSR 275) for now? I'd love to adopt any new API if it's kind-of baked out :-) but I'll have to figure out how it works, so maybe someone can give me some advice on where to go.

**Comment by keilw** [comment]
Thanks for your interest. **JSR 385** is not "finished" it has just started with a successful JCP Creation Review. So although every API element you find in **JSR 363** (not 275 which never finished due to various factors, the lack of an IoT nearly 10 years ago when we proposed the Public Review of 275 being a rather influencial one) was carried over and therefore as stable as 1.0, you may want to go for JSR 363 for now especially in production. A large number of projects and commercial products use the JSR 363 API. Such as
- [PCP Parfait](https://github.com/performancecopilot/parfait)
- [Eclipse SmartHome](https://www.eclipse.org/smarthome/) and products or projects derived from it like OpenHAB or Magenta SmartHome by Deutsche Telekom
- [Apache SIS](http://sis.apache.org/) from version 0.8
- [Physikal](https://github.com/Tenkiv/Physikal) a Kotlin port on top of this implementation

You asked this in uom-se which while not the Reference Implementation is functionally compatible, passes the TCK and is used by all the mentioned solutions, therefore you find it more often all the way to production stage or commercial products if they use e.g. Eclipse SmartHome or others.

The RI of JSR 385, Indriya was released as [1.0](https://github.com/unitsofmeasurement/indriya/releases/tag/1.0) implementing JSR 363. It is based on this project. The 1.0 release is nearly identical, very few new elements were added to give them a try, but the old ones look similar. The package namespace uses "tec.units" like the last RI that is the only difference. I hope this is an acceptable change, but if you use mostly API and SPI elements, migrating may work as easy as replacing a few JAR files with no or very few code changes. I hope this answers your question? Happy to get your input on JSR 385, but if you want to just use the API use JSR 363 till about a year from now. And depending on how easy you'd like to migrate some day use either this implementation or Indriya 1.0. If most available elements are accessed from `ServiceProvider`, differeces are minimal.

**Comment by feliksik** [comment]
Thanks for your swift and elaborate response, Werner! Much appreciated. I will aim for this project then (understanding it's fancier than the RI but not as new as the JSR-385 one), as I'm dealing with tons of new stuff at the moment.
I am aiming to run it as OSGi bundle, and I notice the maven-packages nicely have the OSGi bundle headers already. Thanks!!!
