### ISSUE TITLE
Quantity#inverse() - Naming is ambiguous

### ISSUE THREAD

**Issue by andi-huber** [unitsofmeasurement/uom-se#194]
Using the `Quantity#inverse()` method had me confused and the java-doc does not provide any clarification: 

In math terminology the term 'inverse' can be applied to any function, without being specific. 

The API in this case declares `Quantity#inverse()` as being the 'inverse of multiplication'. A more precise naming would have been `Quantity#reciprocal()`. But anyway, at least the java-doc could be improved with mentioning that the reciprocal is meant.

Same applies to `Unit#inverse()`.

Great work, though!
Cheers, Andi

**Comment by andi-huber** [comment]
... I had it confused with the 'additive inverse', which is not provided by the API. (Which could be there for symmetry, I guess.)

If there's any chance to improve the API I'd propose adding/replacing:
- `Quantity#negate()` as the 'Additive Inverse' (no change in Unit)
- `Quantity#reciprocal()` as the 'Multiplicative Inverse'

**Comment by keilw** [comment]
Hi @andi-huber, thanks for your input and suggestions. As they are related to the public API, not an implementation, could you please post relevat parts to https://github.com/unitsofmeasurement/unit-api/issues.

So you are suggesting to add two methods in `Quantity`: `negate()` and `reciprocal()`? While leaving the `inverse()` method in `Unit` as it is? Not sure, if that would make things clearer, because `Quantity.inverse()` is basically a wrapper around `Unit.inverse()`. An official Java standard must leave existing method signatures in place for some time. With he JDK only Java 10 or 11 will start removing whole features like JavaFX, CORBA, or Swing. Please raise a ticket in the API project so we can discuss it for JSR 385. this implementation will only handle bugs that arise, but it is not going to implement JSR 385 because Indriya, largely inspired by uom-se will be a universal RI for all supported platforms (currently we no longer target Java ME because no ME Embedded 9 is on the horizon)
