### ISSUE TITLE
Add United States customary units

### ISSUE THREAD

**Issue by GregJohnStewart** [unitsofmeasurement/uom-se#218]
Apologies if this has been hashed out before, but I would love it if there was the [US Customary Units](https://en.wikipedia.org/wiki/United_States_customary_units) included in this codebase. 

I recognize the superiority of Metric/ SI, but there us a large group of people (Americans) that refuse to switch. I am currently working on an app that needs to be flexible to cover as many units as possible, and it is likely that users will want to be able to use these units.

Also wondering where I might find code examples of using this library?

**Comment by keilw** [comment]
There is, it's under https://github.com/unitsofmeasurement/uom-systems. Note uom-se is outdated and except for a critical bug will no longer be maintained because Unit-API 2.x is already out since 2019 and more advanced versions of all these libraries.
Unless you have some very special case that limits you to stick with uom-se, I recommend upgrading to [Indriya](https://github.com/unitsofmeasurement/indriya), allowing you to use versions 2.x of Unit Systems including the Common Unit Systems which contain Imperial or US Customary. 

HTH,
Werner
