### ISSUE TITLE
US Units deleted?

### ISSUE THREAD

**Issue by aw1621107** [unitsofmeasurement/uom-se#71]
Commit a1cfb64 seems to have deleted tec.uom.se.unit.US.java. Was this intended? Doesn't look to be related to the commit message?

**Comment by keilw** [comment]
Yes of course it was, please see https://github.com/unitsofmeasurement/uom-systems/tree/master/common. It may just like the special SI system require a SE specific variant (similar to JSR 354 with 2 identical RIs;-) but the key is to have smaller modular bundles instead of a monolithic big chunk. We already do what Java only plans with V9 (Jigsaw)

**Comment by keilw** [comment]
Sorry if the commit message sometimes refers to a different task, but the overall aim (clarify getSymbol() in this case) is met, so it's not random.
JIRA maker's totally fucked up decision to destroy IDE support for their products makes the java.net JIRA a second class citizen when committing from Eclipse or other IDEs I'm afraid, but uom-se like other modules is not in scope of the main JSR and its JIRA anyway;-)

**Comment by keilw** [comment]
Hope this answers your question, closing it now

**Comment by aw1621107** [comment]
Ah, that makes sense. Thank you for explaining!

**Comment by aw1621107** [comment]
Guess my only complaint is that maven cannot seem to compile uom-systems/ucum at this time... Looking for uom-se-0.8-SNAPSHOT, and if I change uom-se's build to that, seems the movement of AbstractUnit.ONE elsewhere breaks the build. Luckily, I don't think I need that particular part, though.

**Comment by keilw** [comment]
Thanks, but that has another reason. ONE had to be moved into the most basic Unit system (e.g. tec.uom.se.unit.Units) because of an issue the AbstractUnit place had caused the method Unit.asType() in all implementations. A quantity like Dimensionless was not visible that way. Will fix the dependency. As of now UCUM is the only system targeted primarily at SE, all others should exist for RI and other implementations like SE-port. See https://github.com/unitsofmeasurement/si-units/issues/8 I would personally prefer the "classifier" option, making it a bit easier to handle Maven modules. They share the same groupId/artifactId, so e.g. the Java SE 8+ variant would be like "si-impl-X.Y-jdk8" (or -javase8)
While the one without refers to the RI.

**Comment by keilw** [comment]
A distinct task is also created here: https://github.com/unitsofmeasurement/uom-se/issues/72 Beside, both uom-systems and si-units got tasks about artifact-naming. As of now, UCUM also uses uom-se 0.8-RC1. Still pending JCenter deploy, but if you check out latest uom-se (already at RC1) it should work. All other dependencies are 0.8-RC3 of artifacts already out on Sonatype, too.

**Comment by aw1621107** [comment]
Hmmm... Is uom-se supposed to be fully useable? Got some ClassCastException when mixing uom.se.* with systems.uom.common.US.*.

And is formatting not fully implemented in unit-ri?

**Comment by keilw** [comment]
Of course it is, but unit-ri is completely Locale-agnostic, therefore the SimpleUnitFormat does not rely on ResourceBundles like the SE version. There should be no dependency to uom-se in US right now, but as prepared by https://github.com/unitsofmeasurement/uom-systems/issues/8 and a similar task in SI, you'll have to use the correct classifier for JDK 8 (and above) as opposed to ME8/JDK 7 or below.

**Comment by keilw** [comment]
You rarely find JSRs where multiple implementations (inside the same VM) would work properly. I had to apply a lot of tricks to isolate e.g. different EE and Web apps from each other where multiple JSF implementations were used.

**Comment by aw1621107** [comment]
Hmmm, didn't know you could do that. Looks like I'll be messing with maven for the next while...

Sorry for all the questions; this is mostly new stuff for me. Hopefully once I finish the thing I'm working on I can try to help out some.

**Comment by keilw** [comment]
That's more of a challenge for UOM-SE, since it currently doesn't have SimpleFormat. Though this ticket is not going to vanish, the others in uom-systems or si-units could be better suited for future discussions ;-)

**Comment by keilw** [comment]
It works fairly well in RI, where you're free to raise tickets could be https://github.com/unitsofmeasurement/uom-systems, if you spot something around US or other systems. Please don't mention it here, unless it is really a genuine UoM-SE problem.
