### ISSUE TITLE
OldQuantityFactory

### ISSUE THREAD

**Issue by otaviojava** [unitsofmeasurement/uom-se#85]
Proxy classes

We had a discussion about the classes that need to do proxy and about the consequence of these classes on lesser performance.

But still there are two classes:
- ProxyQuantityFactory
- OldProxyQuantityFactory

Is there any reason to these classes stay on uom-se ?

**Comment by otaviojava** [comment]
@keilw what do you think?

**Comment by keilw** [comment]
Especially the "old" variant is related to https://java.net/jira/browse/UNITSOFMEASUREMENT-77, I assigned it to Martin (knowning he was quite busy lately and could not provide much input since the EDR) since he did most of that in JSR 275. There is no reason why https://github.com/unitsofmeasurement/uom-se/blob/master/src/main/java/tec/uom/se/internal/quantity/DefaultQuantityFactoryService.java could not register multiple QuantityFactory implementations.
The problem with DefaultQuantityFactory is, it does not offer its creation to Quantities, but consumes it (unlike JSR 354) from there. This may have to be revisited.

What seems problematic about ProxyQuantityFactory is having to know quantity types. So say Torque or Action are now defined in the SI module, they may not work.

Do not remove any of them. Feel free to add some tests here https://github.com/unitsofmeasurement/si-units/tree/master/impl/src/test/java8/si/uom (note, "java" is for the RI, "java8" for uom-se) to see, how new quantities work. At most, if ProxyQuantityFactory gave troubles compared to DefaultQuantityFactory mark it @deprecated after you prove by JUnit tests it cannot handle certain new quantities. Do not touch the "old" one until we joinly handled the JIRA ticket. If Martin was not able to help us with that, we'll discuss it with Leo and Jean-Marie when they have a moment for it. Generally there are 2 flavors of typesafe Unit handling. This C# library uses quantity types directly, see https://github.com/keilw/QuantityTypes/blob/master/Source/Examples/WpfExample/ViewModel.cs.
Especially under .NET, also inspired by Andrew Kennedy's work for F#. Other examples like Boost for C++ (http://www.boost.org/doc/libs/1_51_0/doc/html/boost_units/Examples.html#boost_units.Examples.QuantityExample, also mentioned by the Spec) use a Quantity<Q> notation similar to what most of our current implementations allow. We have to properly handle https://java.net/jira/browse/UNITSOFMEASUREMENT-77 then we can decide what to do with OldProxyQuantitFactory.

**Comment by keilw** [comment]
Guess we could factor them out into an optional extension module probably uom-lib.

**Comment by keilw** [comment]
Will move `OldQuantityFactory `to demos, but `ProxyQuantityFactory `remains for flexibility reasons.
